name: Integration Tests
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: IntegrationTest
        run: swift test --filter FilterRepositoryIntegrationTests
