name: Integration Tests
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Integration Tests
        run: swift test --filter FilterRepositoryIntegrationTests
